name: perpus_go
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  get: ^4.7.2
  flutter_rating_bar: ^4.0.0
  intl: ^0.18.1 
  flutter_pdfview: ^1.2.7
  syncfusion_flutter_pdfviewer: ^24.1.41
  url_launcher: ^6.2.5


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  fonts:
    - family: fredoka
      fonts:
        - asset: assets/fonts/static/Fredoka-Regular.ttf
        - asset: assets/fonts/static/Fredoka-Bold.ttf
    - family: nunito
      fonts:
        - asset: assets/fonts/static/Fredoka-Medium.ttf

  assets:
    - assets/images/
    - assets/icon/
    - assets/images/hal1.png
    - assets/images/katalog2.png
    - assets/assets/images/
    - assets/pdf/


